<?xml version="1.0" encoding="UTF-8"?>
<CustomApplication xmlns="http://soap.sforce.com/2006/04/metadata">
    <defaultLandingTab>standard-home</defaultLandingTab>
    <formFactors>Large</formFactors>
    <label>FCST Revenue Navigator</label>
    <tab>standard-Account</tab>
    <tab>standard-Dashboard</tab>
    <tab>standard-Opportunity</tab>
    <tab>standard-Product2</tab>
    <tab>standard-report</tab>
    <tab>standard-Contract</tab>
    <tab>standard-Forecasting3</tab>
    <tab>Actual_Model__c</tab>
    <tab>Configuration_Setting__c</tab>
    <tab>Fiscal_Year_Planning__c</tab>
    <tab>FCST_Gap_Planning_Version__c</tab>
    <tab>Fiscal_Year_Model__c</tab>
    <tab>Planning_Financial_Measure__c</tab>
    <tab>Planning_Version__c</tab>
    <tab>Forecast_Quota__c</tab>
    <tab>FCST_Product_Model__c</tab>
    <tab>FCST_Revenue_Recognization_Product__c</tab>
    <tab>FCST_Settings</tab>
    <tab>FCSTRevRecognitionRules</tab>
    <tab>FCST_Contract__c</tab>
    <tab>FCST_Initial_Forecast__c</tab>
    <tab>FCST_Opportunity_Initial_Forecast__c</tab>
    <tab>FCST_Summary</tab>
    <tab>FCST_Mapping</tab>
    <tab>Fcst_Cost_Center__c</tab>
    <tab>Fcst_Geo_Code__c</tab>
    <tab>Upload_File__c</tab>
    <tab>Fcst_BaseLine_Error_Log__c</tab>
    <tab>Hyperian_Report</tab>
    <tab>FCST_Actual_Upload</tab>
    <tab>FCST_Baseline_Upload</tab>
    <tab>rh2__PS_Rollup_Dummy__c</tab>
    <tab>rh2__PS_Export_Rollups__c</tab>
    <tab>rh2__PS_Exception__c</tab>
    <tab>rh2__RH_Job__c</tab>
    <tab>rh2__PS_Queue__c</tab>
</CustomApplication>
